version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Zipping source..."
      - zip -r function.zip .
  post_build:
    commands:
      - echo "Deploying to Lambda..."
      - aws lambda update-function-code --function-name my-lambda-project-handler --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip


